#!/usr/bin/env bash

export USER_BIN=${HOME}/bin
export JAVA_HOME=/usr/lib/jvm/java-6-oracle
export JRE_HOME=/usr/lib/jvm/java-6-oracle/jre
export JAVA_TOOLS=/opt/javatools
export M2_HOME=${JAVA_TOOLS}/apache-maven/apache-maven-3.2.1
export ANT_HOME=${JAVA_TOOLS}/apache-ant-1.8.2
export FORGE_HOME=${JAVA_TOOLS}/forge/forge-distribution-2.2.0.Final
export JBOSS_HOME=${JAVA_TOOLS}/jboss-as-7.1.1.Final
export JBOSS7_HOME=${JAVA_TOOLS}/jboss-as-7.1.1.Final
export WORKSPACE=${HOME}/workspace
export CATALINA_HOME=${JAVA_TOOLS}/apache-tomcat-6.0.35
export PLAY_HOME=${JAVA_TOOLS}/play2/play-2.2.1/
export JMETER_HOME=${JAVA_TOOLS}/jmeter/apache-jmeter-2.7
export CEYLON_HOME=${JAVA_TOOLS}/ceylon/ceylon-0.4
export VIRTUAL_ENV_DEV=${WORKSPACE}/virtual-env
export RVM_DIST=${VIRTUAL_ENV_DEV}/rvm
export VIRTUAL_ENV_DIST=${VIRTUAL_ENV_DEV}/virtualenv/virtualenv-1.11.2
export VIRTUAL_ENV_VERSION=${VIRTUAL_ENV_DEV}/virtualenv/venv-1.11.2
export NODE_ENV_VERSION=${VIRTUAL_ENV_DEV}/nodeenv/default
export GOROOT=${VIRTUAL_ENV_DEV}/go/go-1.2.1

export WINEARCH=win32
export WINEPREFIX=`pwd ${HOME}`/.wine32

# Export PATH
export PATH=${PATH_BASE}
export PATH=${USER_BIN}:${JAVA_HOME}/bin:${M2_HOME}/bin:${ANT_HOME}/bin:${FORGE_HOME}/bin:${PLAY_HOME}:${VIRTUAL_ENV_DIST}:${GOROOT}/bin:$PATH

# Load RVM, if you are using it
[[ -s $RVM_DIST/scripts/rvm ]] && source $RVM_DIST/scripts/rvm

# VirtualEnv python
[[ -s ${VIRTUAL_ENV_VERSION}/base/bin/activate ]] && source ${VIRTUAL_ENV_VERSION}/base/bin/activate

# Node environment
[[ -s ${NODE_ENV_VERSION}/bin/activate ]] && source ${NODE_ENV_VERSION}/bin/activate
