#!/usr/bin/env bash

export USER_BIN=~/bin
export JAVA_HOME=/opt/java/jdk1.7.0_51
export JRE_HOME=/opt/java/jdk1.7.0_51/jre
export PROYECTOS=/proyectos/projects
export JAVA_TOOLS=/proyectos/javatools
export M2_HOME=${JAVA_TOOLS}/apache-maven/apache-maven-3.1.1
export ANT_HOME=${JAVA_TOOLS}/apache-ant-1.8.2
export FORGE_HOME=${JAVA_TOOLS}/forge/forge-distribution-2.2.0.Final
export DEFAULT_PLUGIN_REPO=/proyectos/lab/java/forge/repository
export JBOSS_HOME=${JAVA_TOOLS}/jboss-as-7.1.1.Final
export JBOSS7_HOME=${JAVA_TOOLS}/jboss-as-7.1.1.Final
export WORKSPACE=/proyectos/work
export CATALINA_HOME=${JAVA_TOOLS}/apache-tomcat-6.0.35
export PLAY_HOME=${JAVA_TOOLS}/play2/play-2.2.1/
export JMETER_HOME=${JAVA_TOOLS}/jmeter/apache-jmeter-2.7
export CEYLON_HOME=${JAVA_TOOLS}/ceylon/ceylon-0.4
export JBAKE_HOME=/opt/jbake/jbake-2.2.1
export RVM_DIST=${HOME}/.rvm
export VIRTUAL_ENV_DIST=${HOME}/virtualenv/virtualenv-1.11.2
export VIRTUAL_ENV_VERSION=$HOME/virtualenv/venv-1.11.2

# Export PATH
export PATH=${PATH_BASE}
export PATH=${JAVA_HOME}/bin:${M2_HOME}/bin:${ANT_HOME}/bin:${FORGE_HOME}/bin:${PLAY_HOME}:${JBAKE_HOME}:${VIRTUAL_ENV_DIST}:$PATH

# Load RVM, if you are using it
[[ -s $RVM_DIST/scripts/rvm ]] && source $RVM_DIST/scripts/rvm

# VirtualEnv python
[[ -s $VIRTUAL_ENV_BASE/base/bin/activate ]] && source $VIRTUAL_ENV_BASE/base/bin/activate
